@OpenRAG.Api_HostAddress = https://localhost:7063
@Token = <set-a-short-lived-access-token-locally>

GET {{OpenRAG.Api_HostAddress}}/api/documents
Accept: application/json
Authorization: Bearer {{Token}}

###

GET {{OpenRAG.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###
