<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-OpenRAG.Worker-12fcdad5-f9a5-4030-8563-4bf8f5d7e6a4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP" />
    <PackageReference Include="DotNetCore.CAP.PostgreSql" />
    <PackageReference Include="DotNetCore.CAP.RabbitMQ" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Mediator.SourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenRAG.Application\OpenRAG.Application.csproj" />
    <ProjectReference Include="..\OpenRAG.Infrastructure\OpenRAG.Infrastructure.csproj" />
    <ProjectReference Include="..\OpenRAG.ServiceDefaults\OpenRAG.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
