<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpenRAG.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenRAG.Application\OpenRAG.Application.csproj" />
    <ProjectReference Include="..\OpenRAG.Domain\OpenRAG.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP" />
    <PackageReference Include="DotNetCore.CAP.PostgreSql" />
    <PackageReference Include="DotNetCore.CAP.RabbitMQ" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" />
  </ItemGroup>

</Project>
